import type { ProjectCardData } from './types';

export const MOCK_PROJECTS: ProjectCardData[] = [
  {
    id: '0001',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'web', label: 'Веб-разработка' },
      { key: 'mobile', label: 'Мобайл-разработка' },
      { key: 'ml', label: 'Машинное обучение' },
      { key: 'design', label: 'Дизайн' },
    ],
    format: 'case',
    competencies: ['Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '00011',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'web', label: 'Веб-разработка' },
      { key: 'engineering', label: 'Инженерия' },
    ],
    format: 'case',
    competencies: ['Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0035',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'mobile', label: 'Мобайл-разработка' },
      { key: 'web', label: 'Веб-разработка' },
      { key: 'ml', label: 'Машинное обучение' },
      { key: 'design', label: 'Дизайн' },
      { key: 'fintech', label: 'FinTech' },
    ],
    format: 'case',
    competencies: ['Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '8201',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'web', label: 'Веб-разработка' },
      { key: 'fintech', label: 'FinTech' },
      { key: 'mobile', label: 'Мобайл-разработка' },
      { key: 'ml', label: 'Машинное обучение' },
    ],
    format: 'paid',
    competencies: ['Frontend', 'Backend', 'ML-инженер', 'Тестировщик', 'Аналитик', 'Аналитик', 'Аналитик', 'Backend', 'ML-инженер', 'Тестировщик', 'Аналитик', 'Аналитик', 'Аналитик'],
    organization: 'ТПУ ОРПА',
    extended: true,
    accentColor: '#28be46',
    description: 'Конструктор мероприятий Т-банка: трёхкомпонентная система, состоящая из конструктора по созданию мероприятий, веб и мобильной версий для просмотра актуальных мероприятий, скачивания деталей мероприятий для просмотра в оффлайн-режиме, получения уведомлений о мероприятиях.',
  },
  {
    id: '0001b',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'web', label: 'Веб-разработка' },
      { key: 'design', label: 'Дизайн' },
      { key: 'mobile', label: 'Мобайл-разработка' },
      { key: 'ml', label: 'Машинное обучение' },
      { key: 'fintech', label: 'FinTech' },
    ],
    format: 'real',
    competencies: ['Frontend', 'Frontend', 'Frontend', 'Frontend', 'Frontend'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0002',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'engineering', label: 'Инженерия' },
      { key: 'ml', label: 'Машинное обучение' },
      { key: 'web', label: 'Веб-разработка' },
      { key: 'mobile', label: 'Мобайл-разработка' },
    ],
    format: 'real',
    competencies: ['Frontend', 'Frontend', 'Frontend', 'Frontend'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0003',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'engineering', label: 'Инженерия' },
      { key: 'mobile', label: 'Мобайл-разработка' },
    ],
    format: 'paid',
    competencies: ['Frontend', 'Backend', 'Mobile'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0004',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'ml', label: 'Машинное обучение' },
      { key: 'web', label: 'Веб-разработка' },
      { key: 'engineering', label: 'Инженерия' },
    ],
    format: 'case',
    competencies: ['ML-инженер', 'Backend', 'Аналитик'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0005',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'web', label: 'Веб-разработка' },
      { key: 'design', label: 'Дизайн' },
    ],
    format: 'paid',
    competencies: ['Frontend', 'Backend', 'Дизайнер'],
    organization: 'ТПУ ОРПА',
  },
  {
    id: '0006',
    title: 'Проект ИСП РАН: Открытый инструмент моделирования',
    directions: [
      { key: 'mobile', label: 'Мобайл-разработка' },
      { key: 'web', label: 'Веб-разработка' },
      { key: 'design', label: 'Дизайн' },
      { key: 'fintech', label: 'FinTech' },
      { key: 'engineering', label: 'Инженерия' },
    ],
    format: 'real',
    competencies: ['Mobile', 'Backend', 'Дизайнер', 'Mobile', 'Backend', 'Дизайнер'],
    organization: 'ТПУ ОРПА',
  },
];