import type { Competence, Skill } from "@/features/my-competencies/model/types.ts";

export const ALL_COMPETENCIES: Competence[] = [
  {
    roleTypeId: 'Frontend',
    roleTypeName: 'Frontend',
    skills: []
  },
  {
    roleTypeId: 'Backend',
    roleTypeName: 'Backend',
    skills: []
  },
  {
    roleTypeId: 'DevOps',
    roleTypeName: 'DevOps',
    skills: []
  },
  {
    roleTypeId: 'ML',
    roleTypeName: 'ML инженер',
    skills: []
  },
  {
    roleTypeId: 'Mobile',
    roleTypeName: 'Mobile',
    skills: []
  },
  {
    roleTypeId: 'Analyst',
    roleTypeName: 'Аналитик',
    skills: []
  },
  {
    roleTypeId: 'Designer',
    roleTypeName: 'Дизайнер',
    skills: []
  },
  {
    roleTypeId: 'QA',
    roleTypeName: 'Тестировщик',
    skills: []
  }
];

export const MY_COMPETENCIES: Competence[] = [
  {
    roleTypeId: 'Frontend',
    roleTypeName: 'Frontend',
    skills: [
      { skillId: '1', skillName: 'React' },
      { skillId: '2', skillName: 'HTML' },
      { skillId: '3', skillName: 'CSS' }
    ]
  },
  {
    roleTypeId: 'Backend',
    roleTypeName: 'Backend',
    skills: [
      { skillId: '9', skillName: 'Java' },
      { skillId: '10', skillName: 'Kotlin' },
      { skillId: '11', skillName: 'Scala' }
    ]
  }
];

export const SKILLS_BY_COMPETENCE: Record<string, Skill[]> = {
  DevOps: [],
  Frontend: [
    { skillId: '1', skillName: 'React.js' },
    { skillId: '2', skillName: 'HTML5' },
    { skillId: '3', skillName: 'CSS3' },
    { skillId: '4', skillName: 'TanStack' },
    { skillId: '5', skillName: 'Query' },
    { skillId: '6', skillName: 'JavaScript' },
    { skillId: '7', skillName: 'TypeScript' },
    { skillId: '8', skillName: 'Redux' },
    { skillId: '12', skillName: 'Vue.js' },
    { skillId: '13', skillName: 'Angular' },
    { skillId: 'fe-1', skillName: 'Next.js' },
    { skillId: 'fe-2', skillName: 'Nuxt.js' },
    { skillId: 'fe-3', skillName: 'Svelte' },
    { skillId: 'fe-4', skillName: 'Zustand' },
    { skillId: 'fe-5', skillName: 'MobX' },
    { skillId: 'fe-6', skillName: 'Pinia' },
    { skillId: 'fe-7', skillName: 'Tailwind' },
    { skillId: 'fe-8', skillName: 'SCSS' },
    { skillId: 'fe-9', skillName: 'БЭМ' },
    { skillId: 'fe-10', skillName: 'Webpack' },
    { skillId: 'fe-11', skillName: 'Vite' },
    { skillId: 'fe-12', skillName: 'Babel' },
    { skillId: 'fe-13', skillName: 'npm' },
    { skillId: 'fe-14', skillName: 'Yarn' },
    { skillId: 'fe-15', skillName: 'pnpm' },
    { skillId: 'fe-16', skillName: 'REST API' },
    { skillId: 'fe-17', skillName: 'GraphQL' },
    { skillId: 'fe-18', skillName: 'WebSocket' },
    { skillId: 'fe-19', skillName: 'gRPC' },
    { skillId: 'fe-20', skillName: 'HTTP' },
    { skillId: 'fe-21', skillName: 'CORS' },
    { skillId: 'fe-22', skillName: 'Axios' },
    { skillId: 'fe-23', skillName: 'Jest' },
    { skillId: 'fe-24', skillName: 'Cypress' },
    { skillId: 'fe-25', skillName: 'Playwright' },
    { skillId: 'fe-26', skillName: 'ESLint' },
    { skillId: 'fe-27', skillName: 'Prettier' },
    { skillId: 'fe-28', skillName: 'Git' },
    { skillId: 'fe-29', skillName: 'GitHub' },
    { skillId: 'fe-30', skillName: 'GitLab' },
    { skillId: 'fe-31', skillName: 'Web Accessibility' },
    { skillId: 'fe-32', skillName: 'DOM API' },
    { skillId: 'fe-33', skillName: 'Flexbox' },
    { skillId: 'fe-34', skillName: 'Grid' },
    { skillId: 'fe-35', skillName: 'JSON' },
    { skillId: 'fe-36', skillName: 'AJAX' },
    { skillId: 'fe-37', skillName: 'SPA' },
    { skillId: 'fe-38', skillName: 'SSR' },
    { skillId: 'fe-39', skillName: 'PWA' },
    { skillId: 'fe-40', skillName: 'DevTools' },
    { skillId: 'fe-41', skillName: 'Lighthouse' },
    { skillId: 'fe-42', skillName: 'CI/CD' }
  ],
  Backend: [
    { skillId: '14', skillName: 'Python' },
    { skillId: '15', skillName: 'Go' },
    { skillId: '9', skillName: 'Java' },
    { skillId: 'be-1', skillName: 'Node.js' },
    { skillId: 'be-2', skillName: 'C#' },
    { skillId: 'be-3', skillName: 'PHP' },
    { skillId: 'be-4', skillName: 'Ruby' },
    { skillId: 'be-5', skillName: 'Django' },
    { skillId: 'be-6', skillName: 'FastAPI' },
    { skillId: 'be-7', skillName: 'Spring Boot' },
    { skillId: 'be-8', skillName: 'NestJS' },
    { skillId: 'be-9', skillName: '.NET' },
    { skillId: 'be-10', skillName: 'Express' },
    { skillId: 'be-11', skillName: 'PostgreSQL' },
    { skillId: '16', skillName: 'SQL' },
    { skillId: 'be-12', skillName: 'MySQL' },
    { skillId: 'be-13', skillName: 'MongoDB' },
    { skillId: 'be-14', skillName: 'Redis' },
    { skillId: 'be-15', skillName: 'ClickHouse' },
    { skillId: 'be-16', skillName: 'Elasticsearch' },
    { skillId: 'be-17', skillName: 'NoSQL' },
    { skillId: 'be-18', skillName: 'Kafka' },
    { skillId: 'be-19', skillName: 'RabbitMQ' },
    { skillId: 'be-20', skillName: 'REST API' },
    { skillId: 'be-21', skillName: 'gRPC' },
    { skillId: 'be-22', skillName: 'GraphQL' },
    { skillId: 'be-23', skillName: 'WebSockets' },
    { skillId: '17', skillName: 'Docker' },
    { skillId: 'be-24', skillName: 'Kubernetes' },
    { skillId: 'be-25', skillName: 'Nginx' },
    { skillId: 'be-26', skillName: 'CI/CD' },
    { skillId: 'be-27', skillName: 'Linux' },
    { skillId: 'be-28', skillName: 'Bash' },
    { skillId: 'be-29', skillName: 'AWS' },
    { skillId: 'be-30', skillName: 'Git' },
    { skillId: 'be-31', skillName: 'ООП' },
    { skillId: 'be-32', skillName: 'SOLID' },
    { skillId: 'be-33', skillName: 'Микросервисы' },
    { skillId: 'be-34', skillName: 'Монолит' },
    { skillId: 'be-35', skillName: 'JWT' },
    { skillId: 'be-36', skillName: 'OAuth 2.0' },
    { skillId: 'be-37', skillName: 'Swagger' },
    { skillId: 'be-38', skillName: 'OpenAPI' },
    { skillId: 'be-39', skillName: 'PyTest' },
    { skillId: 'be-40', skillName: 'JUnit' },
    { skillId: 'be-41', skillName: 'Prometheus' },
    { skillId: 'be-42', skillName: 'Grafana' },
    { skillId: 'be-43', skillName: 'ELK Stack' },
    { skillId: 'be-44', skillName: 'Sentry' },
    { skillId: 'be-45', skillName: 'Асинхронность' },
    { skillId: '10', skillName: 'Kotlin' },
    { skillId: '11', skillName: 'Scala' }
  ],
  ML: [
    { skillId: 'ml-1', skillName: 'Python' },
    { skillId: 'ml-2', skillName: 'NumPy' },
    { skillId: 'ml-3', skillName: 'Pandas' },
    { skillId: 'ml-4', skillName: 'Scikit-Learn' },
    { skillId: 'ml-5', skillName: 'PyTorch' },
    { skillId: 'ml-6', skillName: 'TensorFlow' },
    { skillId: 'ml-7', skillName: 'Keras' },
    { skillId: 'ml-8', skillName: 'XGBoost' },
    { skillId: 'ml-9', skillName: 'LightGBM' },
    { skillId: 'ml-10', skillName: 'CatBoost' },
    { skillId: 'ml-11', skillName: 'Машинное обучение' },
    { skillId: 'ml-12', skillName: 'Глубокое обучение' },
    { skillId: 'ml-13', skillName: 'Нейронные сети' },
    { skillId: 'ml-14', skillName: 'Классические алгоритмы' },
    { skillId: 'ml-15', skillName: 'Регрессионный анализ' },
    { skillId: 'ml-16', skillName: 'Кластеризация' },
    { skillId: 'ml-17', skillName: 'Классификация' },
    { skillId: 'ml-18', skillName: 'Линейная алгебра' },
    { skillId: 'ml-19', skillName: 'Математическая статистика' },
    { skillId: 'ml-20', skillName: 'Теория вероятностей' },
    { skillId: 'ml-21', skillName: 'Feature Engineering' },
    { skillId: 'ml-22', skillName: 'Feature Selection' },
    { skillId: 'ml-23', skillName: 'Предобработка данных' },
    { skillId: 'ml-24', skillName: 'Очистка данных' },
    { skillId: 'ml-25', skillName: 'Валидация моделей' },
    { skillId: 'ml-26', skillName: 'Оценка метрик' },
    { skillId: 'ml-27', skillName: 'Оптимизация гиперпараметров' },
    { skillId: 'ml-28', skillName: 'Optuna' },
    { skillId: 'ml-29', skillName: 'Компьютерное зрение' },
    { skillId: 'ml-30', skillName: 'Обработка текста' },
    { skillId: 'ml-31', skillName: 'NLP' },
    { skillId: 'ml-32', skillName: 'Computer Vision' },
    { skillId: 'ml-33', skillName: 'Transformers' },
    { skillId: 'ml-34', skillName: 'BERT' },
    { skillId: 'ml-35', skillName: 'YOLO' },
    { skillId: 'ml-36', skillName: 'OpenAI API' },
    { skillId: 'ml-37', skillName: 'Hugging Face' },
    { skillId: 'ml-38', skillName: 'SQL' },
    { skillId: 'ml-39', skillName: 'MLOps' },
    { skillId: 'ml-40', skillName: 'MLflow' },
    { skillId: 'ml-41', skillName: 'DVC' },
    { skillId: 'ml-42', skillName: 'Docker' },
    { skillId: 'ml-43', skillName: 'Git' },
    { skillId: 'ml-44', skillName: 'Triton Server' },
    { skillId: 'ml-45', skillName: 'ONNX' },
    { skillId: 'ml-46', skillName: 'FastAPI' },
    { skillId: 'ml-47', skillName: 'CUDA' },
    { skillId: 'ml-48', skillName: 'Обучение моделей' },
    { skillId: 'ml-49', skillName: 'Деплой моделей' },
    { skillId: 'ml-50', skillName: 'А/В тестирование' }
  ],
  Mobile: [
    { skillId: 'mob-1', skillName: 'Swift' },
    { skillId: 'mob-2', skillName: 'Kotlin' },
    { skillId: 'mob-3', skillName: 'Dart' },
    { skillId: 'mob-4', skillName: 'Objective-C' },
    { skillId: 'mob-5', skillName: 'Java' },
    { skillId: 'mob-6', skillName: 'SwiftUI' },
    { skillId: 'mob-7', skillName: 'UIKit' },
    { skillId: 'mob-8', skillName: 'Jetpack Compose' },
    { skillId: 'mob-9', skillName: 'Flutter' },
    { skillId: 'mob-10', skillName: 'React Native' },
    { skillId: 'mob-11', skillName: 'Android SDK' },
    { skillId: 'mob-12', skillName: 'iOS SDK' },
    { skillId: 'mob-13', skillName: 'Xcode' },
    { skillId: 'mob-14', skillName: 'Android Studio' },
    { skillId: 'mob-15', skillName: 'MVVM' },
    { skillId: 'mob-16', skillName: 'VIPER' },
    { skillId: 'mob-17', skillName: 'MVI' },
    { skillId: 'mob-18', skillName: 'MVP' },
    { skillId: 'mob-19', skillName: 'Clean Architecture' },
    { skillId: 'mob-20', skillName: 'REST API' },
    { skillId: 'mob-21', skillName: 'GraphQL' },
    { skillId: 'mob-22', skillName: 'WebSockets' },
    { skillId: 'mob-23', skillName: 'Push Notifications' },
    { skillId: 'mob-24', skillName: 'CoreData' },
    { skillId: 'mob-25', skillName: 'Room' },
    { skillId: 'mob-26', skillName: 'SQLite' },
    { skillId: 'mob-27', skillName: 'Realm' },
    { skillId: 'mob-28', skillName: 'Firebase' },
    { skillId: 'mob-29', skillName: 'App Store' },
    { skillId: 'mob-30', skillName: 'Google Play' },
    { skillId: 'mob-31', skillName: 'Git' },
    { skillId: 'mob-32', skillName: 'Gradle' },
    { skillId: 'mob-33', skillName: 'CocoaPods' },
    { skillId: 'mob-34', skillName: 'SPM' },
    { skillId: 'mob-35', skillName: 'Fastlane' },
    { skillId: 'mob-36', skillName: 'Crashlytics' },
    { skillId: 'mob-37', skillName: 'Amplitude' },
    { skillId: 'mob-38', skillName: 'Postman' },
    { skillId: 'mob-39', skillName: 'Coroutines' },
    { skillId: 'mob-40', skillName: 'GCD' },
    { skillId: 'mob-41', skillName: 'Архитектура мобильных' },
    { skillId: 'mob-42', skillName: 'Мобильная безопасность' },
    { skillId: 'mob-43', skillName: 'Кроссплатформенная разработка' },
    { skillId: 'mob-44', skillName: 'Нативная разработка' },
    { skillId: 'mob-45', skillName: 'Интеграция API' },
    { skillId: 'mob-46', skillName: 'Тестирование мобильных' },
    { skillId: 'mob-47', skillName: 'Жизненный цикл' },
    { skillId: 'mob-48', skillName: 'Оптимизация памяти' },
    { skillId: 'mob-49', skillName: 'Deep Linking' },
    { skillId: 'mob-50', skillName: 'UI Layout' }
  ],
  Analyst: [
    { skillId: 'an-1', skillName: 'Сбор требований' },
    { skillId: 'an-2', skillName: 'Анализ требований' },
    { skillId: 'an-3', skillName: 'Разработка ТЗ' },
    { skillId: 'an-4', skillName: 'Постановка задач' },
    { skillId: 'an-5', skillName: 'Проектирование интеграций' },
    { skillId: 'an-6', skillName: 'REST API' },
    { skillId: 'an-7', skillName: 'SOAP' },
    { skillId: 'an-8', skillName: 'JSON' },
    { skillId: 'an-9', skillName: 'XML' },
    { skillId: 'an-10', skillName: 'SQL' },
    { skillId: 'an-11', skillName: 'PostgreSQL' },
    { skillId: 'an-12', skillName: 'MySQL' },
    { skillId: 'an-13', skillName: 'Проектирование БД' },
    { skillId: 'an-14', skillName: 'Схемы данных' },
    { skillId: 'an-15', skillName: 'BPMN 2.0' },
    { skillId: 'an-16', skillName: 'UML' },
    { skillId: 'an-17', skillName: 'Use Case' },
    { skillId: 'an-18', skillName: 'Sequence Diagram' },
    { skillId: 'an-19', skillName: 'ER Диаграммы' },
    { skillId: 'an-20', skillName: 'DFD' },
    { skillId: 'an-21', skillName: 'IDEF0' },
    { skillId: 'an-22', skillName: 'Микросервисная архитектура' },
    { skillId: 'an-23', skillName: 'Монолитная архитектура' },
    { skillId: 'an-24', skillName: 'Брокеры сообщений' },
    { skillId: 'an-25', skillName: 'Kafka' },
    { skillId: 'an-26', skillName: 'RabbitMQ' },
    { skillId: 'an-27', skillName: 'Постановки бэкенд' },
    { skillId: 'an-28', skillName: 'Постановки фронтенд' },
    { skillId: 'an-29', skillName: 'Тестирование требований' },
    { skillId: 'an-30', skillName: 'Написание документации' },
    { skillId: 'an-31', skillName: 'Confluence' },
    { skillId: 'an-32', skillName: 'Jira' },
    { skillId: 'an-33', skillName: 'Postman' },
    { skillId: 'an-34', skillName: 'Swagger' },
    { skillId: 'an-35', skillName: 'Miro' },
    { skillId: 'an-36', skillName: 'Draw.io' },
    { skillId: 'an-37', skillName: 'Бизнес-процессы' },
    { skillId: 'an-38', skillName: 'Моделирование процессов' },
    { skillId: 'an-39', skillName: 'Оптимизация процессов' },
    { skillId: 'an-40', skillName: 'Описание систем' },
    { skillId: 'an-41', skillName: 'Анализ разрывов' },
    { skillId: 'an-42', skillName: 'Приоритизация бэклога' },
    { skillId: 'an-43', skillName: 'User Stories' },
    { skillId: 'an-44', skillName: 'Job Stories' },
    { skillId: 'an-45', skillName: 'Техническое писательство' },
    { skillId: 'an-46', skillName: 'Интеграционные сценарии' },
    { skillId: 'an-47', skillName: 'Идемпотентность' },
    { skillId: 'an-48', skillName: 'Обработка ошибок' },
    { skillId: 'an-49', skillName: 'Scrum' },
    { skillId: 'an-50', skillName: 'Kanban' }
  ],
  Designer: [
    { skillId: 'ds-1', skillName: 'Figma' },
    { skillId: 'ds-2', skillName: 'Photoshop' },
    { skillId: 'ds-3', skillName: 'Illustrator' },
    { skillId: 'ds-4', skillName: 'Principle' },
    { skillId: 'ds-5', skillName: 'ProtoPie' },
    { skillId: 'ds-6', skillName: 'After Effects' },
    { skillId: 'ds-7', skillName: 'Blender' },
    { skillId: 'ds-8', skillName: 'Miro' },
    { skillId: 'ds-9', skillName: 'FigJam' },
    { skillId: 'ds-10', skillName: 'UI дизайн' },
    { skillId: 'ds-11', skillName: 'UX дизайн' },
    { skillId: 'ds-12', skillName: 'Прототипирование' },
    { skillId: 'ds-13', skillName: 'Проектирование интерфейсов' },
    { skillId: 'ds-14', skillName: 'Дизайн-системы' },
    { skillId: 'ds-15', skillName: 'Создание компонентов' },
    { skillId: 'ds-16', skillName: 'Автолейаут' },
    { skillId: 'ds-17', skillName: 'Переменные Figma' },
    { skillId: 'ds-18', skillName: 'Адаптивный дизайн' },
    { skillId: 'ds-19', skillName: 'Мобильный дизайн' },
    { skillId: 'ds-20', skillName: 'Веб-дизайн' },
    { skillId: 'ds-21', skillName: 'Типографика' },
    { skillId: 'ds-22', skillName: 'Колористика' },
    { skillId: 'ds-23', skillName: 'Иконографика' },
    { skillId: 'ds-24', skillName: 'Векторная графика' },
    { skillId: 'ds-25', skillName: 'Юзабилити-тестирование' },
    { skillId: 'ds-26', skillName: 'UX-исследования' },
    { skillId: 'ds-27', skillName: 'Бенчмаркинг' },
    { skillId: 'ds-28', skillName: 'Анализ конкурентов' },
    { skillId: 'ds-29', skillName: 'User Flow' },
    { skillId: 'ds-30', skillName: 'CJM' },
    { skillId: 'ds-31', skillName: 'Персоны' },
    { skillId: 'ds-32', skillName: 'Wireframes' },
    { skillId: 'ds-33', skillName: 'Анимация интерфейсов' },
    { skillId: 'ds-34', skillName: 'Микровзаимодействия' },
    { skillId: 'ds-35', skillName: 'Дизайн-аудит' },
    { skillId: 'ds-36', skillName: 'А/В тестирование' },
    { skillId: 'ds-37', skillName: 'Продуктовые метрики' },
    { skillId: 'ds-38', skillName: 'Атомарный дизайн' },
    { skillId: 'ds-39', skillName: 'Передача разработки' },
    { skillId: 'ds-40', skillName: 'Дизайн-ревью' },
    { skillId: 'ds-41', skillName: 'Гайдлайны Apple' },
    { skillId: 'ds-42', skillName: 'Material Design' },
    { skillId: 'ds-43', skillName: 'Доступность интерфейсов' },
    { skillId: 'ds-44', skillName: 'Информационная архитектура' },
    { skillId: 'ds-45', skillName: 'Потенциальный путь' },
    { skillId: 'ds-46', skillName: 'Скетчинг' },
    { skillId: 'ds-47', skillName: 'Мокапы' },
    { skillId: 'ds-48', skillName: 'Концепт-дизайн' },
    { skillId: 'ds-49', skillName: 'Jira' },
    { skillId: 'ds-50', skillName: 'Confluence' }
  ],
  QA: [
    { skillId: 'qa-1', skillName: 'Теория тестирования' },
    { skillId: 'qa-2', skillName: 'Тест-дизайн' },
    { skillId: 'qa-3', skillName: 'Тест-кейсы' },
    { skillId: 'qa-4', skillName: 'Чек-листы' },
    { skillId: 'qa-5', skillName: 'Тест-планы' },
    { skillId: 'qa-6', skillName: 'Баг-репорты' },
    { skillId: 'qa-7', skillName: 'Жизненный цикл' },
    { skillId: 'qa-8', skillName: 'Функциональное тестирование' },
    { skillId: 'qa-9', skillName: 'Регрессионное тестирование' },
    { skillId: 'qa-10', skillName: 'Смоук-тестирование' },
    { skillId: 'qa-11', skillName: 'Интеграционное тестирование' },
    { skillId: 'qa-12', skillName: 'Системное тестирование' },
    { skillId: 'qa-13', skillName: 'Кроссбраузерное тестирование' },
    { skillId: 'qa-14', skillName: 'Мобильное тестирование' },
    { skillId: 'qa-15', skillName: 'Тестирование API' },
    { skillId: 'qa-16', skillName: 'Тестирование требований' },
    { skillId: 'qa-17', skillName: 'Граничные значения' },
    { skillId: 'qa-18', skillName: 'Эквивалентное разделение' },
    { skillId: 'qa-19', skillName: 'Попарное тестирование' },
    { skillId: 'qa-20', skillName: 'Позитивное тестирование' },
    { skillId: 'qa-21', skillName: 'Негативное тестирование' },
    { skillId: 'qa-22', skillName: 'Postman' },
    { skillId: 'qa-23', skillName: 'Charles Proxy' },
    { skillId: 'qa-24', skillName: 'Fiddler' },
    { skillId: 'qa-25', skillName: 'DevTools' },
    { skillId: 'qa-26', skillName: 'SQL' },
    { skillId: 'qa-27', skillName: 'Логирование' },
    { skillId: 'qa-28', skillName: 'Linux CLI' },
    { skillId: 'qa-29', skillName: 'Swagger' },
    { skillId: 'qa-30', skillName: 'ADB' },
    { skillId: 'qa-31', skillName: 'Эмуляторы' },
    { skillId: 'qa-32', skillName: 'Симуляторы' },
    { skillId: 'qa-33', skillName: 'Автоматизация тестирования' },
    { skillId: 'qa-34', skillName: 'Python' },
    { skillId: 'qa-35', skillName: 'Java' },
    { skillId: 'qa-36', skillName: 'JavaScript' },
    { skillId: 'qa-37', skillName: 'Selenium' },
    { skillId: 'qa-38', skillName: 'Playwright' },
    { skillId: 'qa-39', skillName: 'Cypress' },
    { skillId: 'qa-40', skillName: 'PyTest' },
    { skillId: 'qa-41', skillName: 'JUnit' },
    { skillId: 'qa-42', skillName: 'Page Object' },
    { skillId: 'qa-43', skillName: 'Allure' },
    { skillId: 'qa-44', skillName: 'Git' },
    { skillId: 'qa-45', skillName: 'CI/CD' },
    { skillId: 'qa-46', skillName: 'Jira' },
    { skillId: 'qa-47', skillName: 'Test IT' },
    { skillId: 'qa-48', skillName: 'Qase' },
    { skillId: 'qa-49', skillName: 'REST' },
    { skillId: 'qa-50', skillName: 'SOAP' }
  ]
};